#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

build_folder=build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cp ../hoofdstukken/voorpagina/*.* $build_folder
cd $build_folder

pandoc voorpagina_1_led_en_knop.md -o ../../boeken/voorpagina_1_led_en_knop.pdf
